/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 31-12ÔÂ-2018 16:18:46 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `miaosha_content` CASCADE
;

DROP TABLE IF EXISTS `miaosha_item` CASCADE
;

DROP TABLE IF EXISTS `miaosha_main` CASCADE
;

/* Create Tables */

CREATE TABLE `miaosha_content`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`main_id` BIGINT NOT NULL,
	`day_time` VARCHAR(50) NULL,
	CONSTRAINT `PK_miaosha_content` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `miaosha_item`
(
	`time_id` BIGINT NOT NULL,
	`title` VARCHAR(200) NULL,
	`now_price` VARCHAR(50) NULL,
	`del_price` VARCHAR(50) NULL,
	`href` VARCHAR(200) NULL,
	`imgsrc` TEXT NULL,
	`img` MEDIUMBLOB NULL
)

;

CREATE TABLE `miaosha_main`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`timestamp` DOUBLE NOT NULL,
	CONSTRAINT `PK_miaosha_main` PRIMARY KEY (`id` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1 
;
